# This should be ONLY loaded by Z (and later other WISE µS)
spring:
  profile: uat

vendor-a:
  password: ${PASSWORD_VENDORA}

app-config-connection-string: ${APP_CONFIGURATION_CONNECTION_STRING}

vendor-wise.url: https://vendor-wise.uat/ 